import { useState, useCallback, useRef } from 'react'

// Pre-generated natural TTS audio (public/audio/).
// English: Kokoro ONNX (Heart/Fenrir, .wav) + edge-tts (Ava/Andrew, .mp3).
// All other languages: edge-tts neural voices (.mp3), female + male.
// Generated by scripts/generate-tts.mjs (Kokoro) and scripts/generate-edge-tts.py (edge).
export interface AudioVoice {
  id: string             // unique key
  name: string           // display name, capitalized, no emoji
  gender: 'f' | 'm'
  file: string           // path under public/
}

export const AUDIO_VOICES: Record<string, AudioVoice[]> = {
  en: [
    { id: 'en-heart',  name: 'Heart',  gender: 'f', file: '/audio/en-f.wav' },
    { id: 'en-fenrir', name: 'Fenrir', gender: 'm', file: '/audio/en-m.wav' },
    { id: 'en-ava',    name: 'Ava',    gender: 'f', file: '/audio/en-f.mp3' },
    { id: 'en-andrew', name: 'Andrew', gender: 'm', file: '/audio/en-m.mp3' },
  ],
  es: [
    { id: 'es-m',  name: 'Lorenzo',  gender: 'm', file: '/audio/es-m.mp3' },
    { id: 'es-f',  name: 'Catalina', gender: 'f', file: '/audio/es-f.mp3' },
    { id: 'es-kf', name: 'Dora',     gender: 'f', file: '/audio/es-kf.wav' },
    { id: 'es-km', name: 'Alex',     gender: 'm', file: '/audio/es-km.wav' },
  ],
  pt: [
    { id: 'pt-f',  name: 'Francisca', gender: 'f', file: '/audio/pt-f.mp3' },
    { id: 'pt-m',  name: 'Antônio',   gender: 'm', file: '/audio/pt-m.mp3' },
    { id: 'pt-kf', name: 'Dora',      gender: 'f', file: '/audio/pt-kf.wav' },
    { id: 'pt-km', name: 'Alex',      gender: 'm', file: '/audio/pt-km.wav' },
  ],
  hi: [
    { id: 'hi-f',  name: 'Swara',  gender: 'f', file: '/audio/hi-f.mp3' },
    { id: 'hi-m',  name: 'Madhur', gender: 'm', file: '/audio/hi-m.mp3' },
    { id: 'hi-kf', name: 'Alpha',  gender: 'f', file: '/audio/hi-kf.wav' },
    { id: 'hi-km', name: 'Omega',  gender: 'm', file: '/audio/hi-km.wav' },
  ],
  fr: [
    { id: 'fr-f',  name: 'Denise', gender: 'f', file: '/audio/fr-f.mp3' },
    { id: 'fr-m',  name: 'Henri',  gender: 'm', file: '/audio/fr-m.mp3' },
    { id: 'fr-kf', name: 'Siwis',  gender: 'f', file: '/audio/fr-kf.wav' },
  ],
  de: [
    { id: 'de-f', name: 'Katja',  gender: 'f', file: '/audio/de-f.mp3' },
    { id: 'de-m', name: 'Conrad', gender: 'm', file: '/audio/de-m.mp3' },
  ],
  sw: [
    { id: 'sw-f', name: 'Rehema', gender: 'f', file: '/audio/sw-f.mp3' },
    { id: 'sw-m', name: 'Daudi',  gender: 'm', file: '/audio/sw-m.mp3' },
  ],
  tr: [
    { id: 'tr-f', name: 'Emel',  gender: 'f', file: '/audio/tr-f.mp3' },
    { id: 'tr-m', name: 'Ahmet', gender: 'm', file: '/audio/tr-m.mp3' },
  ],
  pl: [
    { id: 'pl-f', name: 'Zofia', gender: 'f', file: '/audio/pl-f.mp3' },
    { id: 'pl-m', name: 'Marek', gender: 'm', file: '/audio/pl-m.mp3' },
  ],
  ar: [
    { id: 'ar-f', name: 'Salma',  gender: 'f', file: '/audio/ar-f.mp3' },
    { id: 'ar-m', name: 'Shakir', gender: 'm', file: '/audio/ar-m.mp3' },
  ],
  zh: [
    { id: 'zh-f',  name: 'Xiaoxiao', gender: 'f', file: '/audio/zh-f.mp3' },
    { id: 'zh-m',  name: 'Yunxi',    gender: 'm', file: '/audio/zh-m.mp3' },
    { id: 'zh-kf', name: 'Xiaobei',  gender: 'f', file: '/audio/zh-kf.wav' },
    { id: 'zh-km', name: 'Yunyang',  gender: 'm', file: '/audio/zh-km.wav' },
  ],
  ko: [
    { id: 'ko-f', name: 'Sunhi',  gender: 'f', file: '/audio/ko-f.mp3' },
    { id: 'ko-m', name: 'Injoon', gender: 'm', file: '/audio/ko-m.mp3' },
  ],
  ja: [
    { id: 'ja-f', name: 'Nanami', gender: 'f', file: '/audio/ja-f.mp3' },
    { id: 'ja-m', name: 'Keita',  gender: 'm', file: '/audio/ja-m.mp3' },
  ],
  ru: [
    { id: 'ru-f', name: 'Svetlana', gender: 'f', file: '/audio/ru-f.mp3' },
    { id: 'ru-m', name: 'Dmitry',   gender: 'm', file: '/audio/ru-m.mp3' },
  ],
  it: [
    { id: 'it-f',  name: 'Elsa',   gender: 'f', file: '/audio/it-f.mp3' },
    { id: 'it-m',  name: 'Diego',  gender: 'm', file: '/audio/it-m.mp3' },
    { id: 'it-kf', name: 'Sara',   gender: 'f', file: '/audio/it-kf.wav' },
    { id: 'it-km', name: 'Nicola', gender: 'm', file: '/audio/it-km.wav' },
  ],
  el: [
    { id: 'el-f', name: 'Athina',   gender: 'f', file: '/audio/el-f.mp3' },
    { id: 'el-m', name: 'Nestoras', gender: 'm', file: '/audio/el-m.mp3' },
  ],
  he: [
    { id: 'he-f', name: 'Hila', gender: 'f', file: '/audio/he-f.mp3' },
    { id: 'he-m', name: 'Avri', gender: 'm', file: '/audio/he-m.mp3' },
  ],
}

export function getAudioVoices(langCode: string): AudioVoice[] {
  return AUDIO_VOICES[langCode] ?? []
}

function syllableCount(word: string): number {
  const clean = word.replace(/[^\p{L}]/gu, '')
  if (!clean) return 0.1
  // Vowel groups as syllable proxy (Latin, Cyrillic, Greek, Devanagari)
  const vowels = clean.match(/[aeiouáéíóúàèìòùäëïöüāēīōūăĕĭŏŭаеёиоуыэюяαεηιουω]+/gi)
  if (vowels) return Math.max(1, vowels.length)
  // CJK / Korean: each character ≈ 1 syllable
  const cjk = clean.match(/[぀-鿿가-힯]+/g)
  if (cjk) return cjk.reduce((n, s) => n + s.length, 0)
  return Math.max(1, clean.length / 3)
}

interface WordTiming {
  charStart: number
  end: number    // seconds
}

function buildWordTimings(text: string, duration: number): WordTiming[] {
  const tokens = text.split(/(\s+)/)
  const weights = tokens.map(tok => {
    if (/^\s+$/.test(tok)) return 0
    const syllables = syllableCount(tok)
    const punctPause = /[,;]/.test(tok) ? 0.35 : /[.!?¿¡؟।。？！]/.test(tok) ? 0.55 : 0
    return syllables + punctPause
  })
  const total = weights.reduce((a, b) => a + b, 0) || 1
  let t = 0
  let charPos = 0
  return tokens.map((tok, i) => {
    t += (weights[i] / total) * duration
    const charStart = charPos
    charPos += tok.length
    return { charStart, end: t }
  })
}

export function useAudioTTS() {
  const [isPlaying, setIsPlaying]     = useState(false)
  const [isPaused, setIsPaused]       = useState(false)
  const [charIndex, setCharIndex]     = useState(-1)
  const [currentTime, setCurrentTime] = useState(0)
  const [duration, setDuration]       = useState(0)
  // selected voice id; falls back to first voice of the current language
  const [voiceId, setVoiceId]     = useState<string | null>(null)

  const audioRef   = useRef<HTMLAudioElement | null>(null)
  const timingsRef = useRef<WordTiming[]>([])
  const voiceIdRef = useRef<string | null>(null)
  voiceIdRef.current = voiceId

  const stopAudio = useCallback(() => {
    const audio = audioRef.current
    if (audio) {
      // Detach error handler before clearing src — setting src='' fires an
      // 'error' event we don't want to react to.
      audio.onerror = null
      audio.pause()
      audio.removeAttribute('src')
      audio.load()
      audioRef.current = null
    }
    timingsRef.current = []
  }, [])

  const stop = useCallback(() => {
    stopAudio()
    setIsPlaying(false)
    setIsPaused(false)
    setCharIndex(-1)
    setCurrentTime(0)
    setDuration(0)
  }, [stopAudio])

  const seek = useCallback((t: number) => {
    const audio = audioRef.current
    if (!audio) return
    const clamped = Math.max(0, Math.min(t, audio.duration || 0))
    audio.currentTime = clamped
    setCurrentTime(clamped)
  }, [])

  const restart = useCallback(() => {
    const audio = audioRef.current
    if (audio) {
      audio.currentTime = 0
      setCurrentTime(0)
      audio.play().catch(() => {})
    }
  }, [])

  const speak = useCallback((text: string, ttsLang: string) => {
    const langCode = ttsLang.split('-')[0]
    const voices = AUDIO_VOICES[langCode]
    if (!voices || voices.length === 0) return

    const voice = voices.find(v => v.id === voiceIdRef.current) ?? voices[0]

    stopAudio()
    setCharIndex(-1)
    setIsPaused(false)

    const audio = new Audio(voice.file)
    audioRef.current = audio

    audio.addEventListener('loadedmetadata', () => {
      setDuration(audio.duration)
      timingsRef.current = buildWordTimings(text, audio.duration)
    })
    audio.addEventListener('durationchange', () => { setDuration(audio.duration) })

    audio.addEventListener('timeupdate', () => {
      const t = audio.currentTime
      setCurrentTime(t)
      const timings = timingsRef.current
      if (!timings.length) return
      let idx = 0
      for (let i = 0; i < timings.length; i++) {
        if (t >= timings[i].end) idx = i + 1
        else break
      }
      const tok = timings[Math.min(idx, timings.length - 1)]
      setCharIndex(tok ? tok.charStart : -1)
    })

    audio.addEventListener('play',  () => { setIsPlaying(true); setIsPaused(false) })
    audio.addEventListener('pause', () => { setIsPaused(true) })
    audio.addEventListener('ended', () => {
      setIsPlaying(false)
      setIsPaused(false)
      setCharIndex(-1)
      setCurrentTime(0)
      audioRef.current = null
    })

    audio.play().catch(() => { setIsPlaying(false) })
  }, [stopAudio])

  const pause  = useCallback(() => { audioRef.current?.pause() }, [])
  const resume = useCallback(() => { audioRef.current?.play() }, [])

  return {
    isPlaying, isPaused, charIndex, currentTime, duration,
    speak, pause, resume, stop, seek, restart,
    voiceId, setVoiceId, getAudioVoices,
  }
}
